### ISSUE TITLE
[PE-D][Tester C] Cluttered Command Summary

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T10-1/tp#107] opened 2023-11-03 20:53 UTC
![Screenshot from 2023-11-03 16-56-47.png](https://raw.githubusercontent.com/LicongHuang/ped/main/files/4483d0d0-2736-4608-bebd-f83f345b76d7.png)

There is probably some issues with alignment in the UG markdown, causing part to also be misaligned.

-------------
Labels: `severity.High` `type.DocumentationBug`
original: LicongHuang/ped#6

**Comment by lshaoqin** [comment] 2023-11-06 13:17
Duplicate of #115

**Closed as completed by lshaoqin** 2023-11-06 13:17 UTC
